{% set version = '1.0-15' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ash
  version: {{ version|replace("-", "_") }}

source:
  fn: ash_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ash_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ash/ash_{{ version }}.tar.gz
  sha256: 8b0a7bc39dd0ce2172f09edc5b5e029347d041a4d508bbff3f3fd6f69450c2ab

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('ash')"           # [not win]
    - "\"%R%\" -e \"library('ash')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ash
  license: GPL (>= 2)
  summary: David Scott's ASH routines ported from S-PLUS to R.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
