travis:
  secure:
    BINSTAR_TOKEN: HIK10M7GXh8WzWTOsoYsEs8JLirpyQIoA04cLroAIbMiGa0I0SG6dezQDguP9ZjMNuH6BmNbIltZVBxyZTKSputzNb7tclGN9yvUalfVdoEHOVQukXh51RAXy000UsmHh59BZd1nR8Kr3ZpNxwwK+TlIyY/BfJXEqXnl9Mp06U1nE7xob5zCQI36SqqASqM5hnlnG+7GP/x2Yx8BPG6iA6+ICIIkRx2ukq4bBxK3LSPwGjCE62n0MSfaL8v0pa+0uKmZPFHWgieNpGb1YYg9t9UvoKK1vQ1fDz1xLRwCyf+Kzg5po7ICbp9eeDuLNY2O8KWFJNvjPuMK2rwVZit4CHHwadmYSg5Xdj5WgdSzafl+hAAxUI4aTSiF6EM19rzdeWnpw62bv/8cBs82f5Zze936JdEW6QAy19Lebz9JsVPOINS85vIW7+wKiKTeIjlBFNg+oAmpzYHpn2EpXtz4SCJOpLNS97PsccnJ5tadz5N0eMJ0B5vFrpuBrjy2SgGgkndkXBgp2iM54K0+XJVQqgY5kYszLiQquqeW7QNLOZrJ59NaSLs14fQDq9EB6i754wgdzddYVvZHE7HahxxIlcrYJ97W9Ta2QndB3vS6DdwPEkWNjd93FWlIQYihXzCxuqa8MKxvWMpTPeMU9nRmTgD07gILcRNA/E34IOBtxqU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
