appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: IYzAe2BeDCf5rerHm83vcpBgAqUMpNml30XtBbpre4RQuycjZBUh2yUTdD1IwAuW6+HUCp8dp7Cv1Qq/mHBrBOtRQVfSpXensahkiEfa0wmpDhjWM311z39rwkSrb3SMSTFOStzYitZBNHUrUBVwXumOl1t3D9JnRHRyKdij6Iv6hqA7n37Yi1AysKMieSZdKc7uW5qv05Gf+J9klu2CnHicBnsDTxbzQ77ic3boYYJJ6eCFtf8yxM6+MalA/m+l0pGe944vP4L/wKqFK4gWZ90ahkPwKIr86QX4SOLQ7HZYtyhNDsP50FitHS8uO1n9Kra59rlidyMv15T4ykacoM/0IMj/Dc9pJagCOU8dT15R5mqHYqgZF4tLR+Rz1NjwAelQvLs82Vdd9dHNfwRdXnOpMif3m+OWjyiopFXME5j5ne87GK/IkzJjOxJBMFORzMEoqGaksWzoT774Qj+UTIPUtXltUOSiy2wbX4g+JqRVRQkJkGYFHrRkcQXqnrwM/VZu8z1rkDCxMTbcy701nWMS+0eSEU0XlG0wzaGjIqU0i6g2jCdq/UOR7MNUvoGc7rp3Z7hz5+COtVW1cqjqdIfn3YEFL5z535KpZGynueqaE04IddUcECv3MP/3eqFXIWrxMzi+aDNaxZj2uVBG2i4wURmSOHp6f9ldhNd9aFw=}
